---
#
# Use nix-emacs-ci for travis CI
# URL: https://github.com/purcell/nix-emacs-ci
#
language: nix
os:
  - linux

env:
  global:
  - CACHIX_CACHE=ardumont-markdown-toc
  matrix:
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-27-2

matrix:
  fast_finish: true

install:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
  - nix-env -iA nixpkgs.cachix
  - cachix authtoken $CACHIX_AUTH_TOKEN
  - cachix use $CACHIX_CACHE
  - nix path-info --all > /tmp/store-path-pre-build
  # The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - nix-env -iA nixpkgs.cask
  - comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push $CACHIX_CACHE

script:
  - pwd
  - make install test
