#
# dired-rsync CI definition
#

test-dired-rsync:
  image: debian:latest
  before_script:
    # Install evm
    - git clone https://github.com/rejeep/evm.git ~/.evm
    - export PATH="$HOME/.evm/bin:$PATH"
    - evm config path /tmp
    - evm list
    # use this version of emacs for tests
    - evm install "${EVM_EMACS}" --use --skip
    - emacs --version
    # install cask
    - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
    - export PATH="$HOME/.cask/bin:$PATH"
    # Check that cask is finding the right emacs
    - cask emacs --version
    # Install elisp dependencies
    - cask install
  script:
    - if [ "$EVM_EMACS" != "emacs-git-snapshot-travis-linux-xenial" ] ; then cask exec ert-runner dired-rsync-ert.el ; fi
    - cask build
    - cask exec ert-runner dired-rsync-ert.el
  parallel:
    matrix:
      - EVM_EMACS: [emacs-24.4-travis, emacs-24.5-travis, emacs-25.1-travis, emacs-25.2-travis, emacs-25.3-travis, emacs-26.1-travis-linux-xenial, emacs-26.3-travis-linux-xenial, emacs-git-snapshot-travis-linux-xenial, remacs-git-snapshot-travis]
      
